name: 🤖 Build

on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
      source-file-path:
        required: true
        type: string
      tests-file-path:
        required: true
        type: string

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub action'
        uses: actions/checkout@v3

      - name: Setup dotnet ${{ inputs.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
          
      - name: Display dotnet version
        run: dotnet --version
